spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/test?userUnicode=true&charsetEncoding=utf-8&userSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9292